### ISSUE TITLE
Add an option to undecorate new windows by default

### ISSUE THREAD

**Issue by jmaris** [sunwxg/gnome-shell-extension-undecorate#1]
Hey :) I don't know if this would be possible but i think it'd be really cool to be able to undecorate new windows by default ? Thanks again for the awesome extension

**Comment by sunwxg** [comment]
Hi

When undecorate some window,  it will look weird,like gnome-control-center.
So not all windows are adapted to undecorate or decorate action. I think it
is better to undecorate window manually by person.

Thanks for your suggestion.

**Comment by jmaris** [comment]
you make a valid point, once again thanks for your awesome extension :D 
Will close this report :)

**Comment by 4fort** [comment]
Sorry for bumping. 

> When undecorate some window,  it will look weird

or maybe once the window is undecorated, it will be undecorated always even after reopening, like whitelisting specific apps to be undecorated.
