### ISSUE TITLE
Add a shortcut to undecorate a window (rather than clicking a menu option)

### ISSUE THREAD

**Issue by JasoonS** [sunwxg/gnome-shell-extension-undecorate#3]
It would be great to add a shortcut to undecorate a window (rather than clicking a menu option).

Something similar to how https://extensions.gnome.org/extension/545/hide-top-bar/ allows you to create a custom shortcut in its options to hide the top bar.

But great plugin, thanks!!

**Comment by sunwxg** [comment]
Good idea. It will make extension more complex,  I want to keep extension really simple. Thanks for your recommendation.
